/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/app-logo/index.vue')['default']
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GlobalWatermark: typeof import('./src/components/global-watermark/index.vue')['default']
    IconCarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    IconCarbonAsleep: typeof import('~icons/carbon/asleep')['default']
    IconCarbonCheckmark: typeof import('~icons/carbon/checkmark')['default']
    IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonDocument: typeof import('~icons/carbon/document')['default']
    IconCarbonFitToScreen: typeof import('~icons/carbon/fit-to-screen')['default']
    IconCarbonLaptop: typeof import('~icons/carbon/laptop')['default']
    IconCarbonLocked: typeof import('~icons/carbon/locked')['default']
    IconCarbonMaximize: typeof import('~icons/carbon/maximize')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconCarbonMinimize: typeof import('~icons/carbon/minimize')['default']
    IconCarbonNotification: typeof import('~icons/carbon/notification')['default']
    IconCarbonPinFilled: typeof import('~icons/carbon/pin-filled')['default']
    IconCarbonReset: typeof import('~icons/carbon/reset')['default']
    IconCarbonRightPanelClose: typeof import('~icons/carbon/right-panel-close')['default']
    IconCarbonRightPanelOpen: typeof import('~icons/carbon/right-panel-open')['default']
    IconCarbonSearch: typeof import('~icons/carbon/search')['default']
    IconCarbonSettings: typeof import('~icons/carbon/settings')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCarbonUser: typeof import('~icons/carbon/user')['default']
    LockScreen: typeof import('./src/components/lock-screen/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCommand: typeof import('./src/components/search-command/index.vue')['default']
  }
}
